/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASK1_H_RPCGEN
#define _ASK1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data1 {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct data1 data1;

struct data2 {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct data2 data2;

struct data3 {
	double r;
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct data3 data3;

struct out2 {
	struct {
		u_int A_len;
		double *A_val;
	} A;
};
typedef struct out2 out2;

struct out3 {
	struct {
		u_int B_len;
		double *B_val;
	} B;
};
typedef struct out3 out3;

#define VECTOR_ASK1 0x12345678
#define INNERPRODUCT_VERSION 2

#if defined(__STDC__) || defined(__cplusplus)
#define INNERPRODUCT 1
extern  int * innerproduct_2(data1 *, CLIENT *);
extern  int * innerproduct_2_svc(data1 *, struct svc_req *);
extern int vector_ask1_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INNERPRODUCT 1
extern  int * innerproduct_2();
extern  int * innerproduct_2_svc();
extern int vector_ask1_2_freeresult ();
#endif /* K&R C */
#define AVGEXEY_VERSION 3

#if defined(__STDC__) || defined(__cplusplus)
#define AVGEXEY 1
extern  out2 * avgexey_3(data2 *, CLIENT *);
extern  out2 * avgexey_3_svc(data2 *, struct svc_req *);
extern int vector_ask1_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AVGEXEY 1
extern  out2 * avgexey_3();
extern  out2 * avgexey_3_svc();
extern int vector_ask1_3_freeresult ();
#endif /* K&R C */
#define GIN_VERSION 4

#if defined(__STDC__) || defined(__cplusplus)
#define GIN 1
extern  out3 * gin_4(data3 *, CLIENT *);
extern  out3 * gin_4_svc(data3 *, struct svc_req *);
extern int vector_ask1_4_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GIN 1
extern  out3 * gin_4();
extern  out3 * gin_4_svc();
extern int vector_ask1_4_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data1 (XDR *, data1*);
extern  bool_t xdr_data2 (XDR *, data2*);
extern  bool_t xdr_data3 (XDR *, data3*);
extern  bool_t xdr_out2 (XDR *, out2*);
extern  bool_t xdr_out3 (XDR *, out3*);

#else /* K&R C */
extern bool_t xdr_data1 ();
extern bool_t xdr_data2 ();
extern bool_t xdr_data3 ();
extern bool_t xdr_out2 ();
extern bool_t xdr_out3 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASK1_H_RPCGEN */
