/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"

//α ερώτημα
/*
* Το εσωτερικό γινόμενο των δύο διανυσμάτων Χ ∙ Υ (επιστροφή: ένας ακέραιος αριθμός)
*/
int* innerproduct_2_svc(data1 *argp, struct svc_req *rqstp)
{
	static int  result;
	int res=0;// "μετρητης" που κραταει το αποτελεσμα Χ*Υ(πχ Χ1*Υ1=res, άρα res+X2*Y2)
	int i;
	
	for(i=0;i<argp->n;i++)
	{
		res=(argp->X.X_val[i]*argp->Y.Y_val[i])+res;//τυπος εσωτερικου γινομενου
		printf("X%d= %d\n",i+1,argp->X.X_val[i]);
		printf("Y%d= %d\n",i+1,argp->Y.Y_val[i]);
	} 

	//DEBUG ελεγχω αν τα αποτελεσματα στον client και στον server ειναι ιδια
	printf("X*Y = %d\n",res);
	printf("*****************************************\n");
	result=res; //εκχωρω το αποτελεσμα που βρηκα στη μεταβλητη result ωστε να τη στειλω στον client για εμφανιση

	return &result; //επιστρεφει στον client το αποτελεσμα
}

out2* avgexey_3_svc(data2 *argp, struct svc_req *rqstp)
{
	static out2  result;
	int i;
	double sumX=0.0;
	double sumY=0.0;
	double avgX, avgY;
	result.A.A_len=2;//το μεγεθος του πινακα ειναι 2. στη πρωτη θεση εχουμε τον ΜΟ του Χ, στη δευτερη τον ΜΟ του Υ
	result.A.A_val=(double *)malloc(result.A.A_len*sizeof(double));//δεσμευουμε μνημη για τις τιμες του πινακα Α

	// Μέσος όρος Χ
	for(i=0;i<argp->n;i++)
	{
		sumX+=argp->X.X_val[i]; //argp=παιρνει τις εισοδους απο το client
		avgX=sumX/argp->n;
		printf("X%d= %d\n",i+1,argp->X.X_val[i]);	
	}
	printf("Ex(%.2lf)= SumX(%.2lf) / n(%d) \n",avgX, sumX, argp->n);
	printf("*****************************************\n");
	//Μέσος όρος του Υ
	for(i=0;i<argp->n;i++)
	{
		sumY+=argp->Y.Y_val[i]; //argp=παιρνει τις εισοδους απο το client
		avgY=sumY/argp->n;
		printf("Y%d= %d\n",i+1, argp->Y.Y_val[i]);
		
	}
	printf("Ey(%.2lf)= SumY(%.2lf) / n(%d) \n",avgY, sumY, argp->n);
	printf("*****************************************\n");
	result.A.A_val[0]=avgX;//στη πρωτη θεση του πινακα εχουμε τον ΜΟ του Χ
	result.A.A_val[1]=avgY;//στη δευτερη θεση του πινακα εχουμε τον ΜΟ του Υ
	
	return &result; //στελνουμε το αποτελεσμα στον client
}

//γ ερώτημα
/*
* Το γινόμενο r*(Χ+Y) (επιστροφή: ένα διάνυσμα-πίνακας πραγματικών αριθμών μήκους n)
*/

out3* gin_4_svc(data3 *argp, struct svc_req *rqstp)
{
	static out3  result;
	int i;
	double ans;
	result.B.B_len=argp->n; //το μεγεθος του πινακα Β ειναι το n που δινει ο χρηστης
	result.B.B_val=(double *)malloc(result.B.B_len*sizeof(double)); //δεσμευουμε μνημη για τις τιμες του πινακα Β

	for(i=0;i<argp->n;i++)
	{
		ans=argp->r*(argp->Y.Y_val[i]+argp->X.X_val[i]); //argp=παιρνει τις εισοδους απο το client, τυπος=r*(X+Y)
		//Εκτυπωση αποτελεσματων
		printf("r = %lf\n", argp->r);
		printf("X%d= %d\n",i+1, argp->X.X_val[i]);
		printf("Y%d= %d\n",i+1, argp->Y.Y_val[i]);
		
		result.B.B_val[i]=ans;//εκχωρουμε το αποτελεσμα στον πινακα Β
		printf("%lf *  (%d + %d )=  %lf\n",argp->r, argp->X.X_val[i],argp->Y.Y_val[i], ans); //DEBUG
		
	}

	return &result; //Στελνουμε το αποτελεσμα στον client
}
